function getLog() {
    cat << EOF
:logo: [@/logo.eia]

-- Changelog --

:h3: This file is autogenerated from git commits!

#Style @/style.eds
EOF

    last=
    
    for i in $(git log --pretty=format:%H); do
        ver=$(git show $i:VERSION | cut -d+ -f1)
        [[ "" == "$ver" ]] && ver="Old"

        if [[ "$last" != "$ver" ]]; then
            echo ""
            echo "-- "$ver" --"
            echo ""
            last=$ver
        fi
    
        line=$(git log -1 --pretty=format:%s "$i")
        if [[ "" != "$line" ]]; then
            ch="|*"
    
            echo $line | grep -q -i "add" && ch="|+"
            echo $line | grep -q -i "rem" && ch="|-"
            echo $line | grep -q -i "fix" && ch="|!"
            echo $line | grep -q -i "update" && ch="|!"
    
            echo "$ch $line"
        fi
    done
    
    last=ver
    echo ""
    echo ":center: --- EEE Sees all ---"
    
}

getLog 2>/dev/null
