#!/usr/bin/env bash

function getLog() {
    cat << EOF
#Style @/style.eds
:logo: [@/logo.eia]

-- Changelog --

:h3: Note: This page is autogenerated from git commits!

-- Upcoming --

EOF

    last=
    current=$(cat VERSION)

    echo "" > lol.txt

    for i in $(git log master --pretty=format:%H); do
        ver=$(git show $i:VERSION | cut -d+ -f1)
        echo "$i:$ver" >> lol.txt
        if [[ "" != "$ver" ]]; then
            if [[ "$last" != "$ver" ]]; then
                if [[ "$current" != "$ver" ]]; then
                    if [[ "$last" != "" ]]; then
                        echo ""
                        echo "-- $last --"
                        echo ""
                    else
                        echo ""
                        echo "-- $current --"
                        echo ""
                    fi
                fi
                last=$ver
            fi
    
            line=$(git log -1 --pretty=format:%s "$i")
            if [[ "" != "$line" ]]; then
                ch="|*"
    
                echo $line | grep -q -i "add" && ch="|+"
                echo $line | grep -q -i "impl" && ch="|+"

                echo $line | grep -q -i "rem" && ch="|-"
                echo $line | grep -q -i "delete" && ch="|-"

                echo $line | grep -q -i "fix" && ch="|!"
                echo $line | grep -q -i "update" && ch="|!"
                echo $line | grep -q -i "reimpl" && ch="|!"
                
                echo $line | grep -q -i "bump" && ch=""
    
                [[ $ch != "" ]] && echo "$ch $line"
            fi
        fi
    done
    
    last=ver
    echo ""
    echo ":center: --- EEE Sees all ---"
}

echo "write $PWD"

getLog 2>/dev/null 1> ./www/changelog.edf
