name: Itch upload
run-name: Upload an itch release build
on:
  workflow_dispatch:
jobs:
  tests-dbg:
    runs-on: ubuntu-latest
    name: Run tests 
    steps:
      - uses: actions/checkout@v3
      - name: Cache zig build
        uses: actions/cache@v4
        env:
          cache-name: cache-zig
        with:
          path: |
            ${{github.workspace}}/.cache/zig
            ${{github.workspace}}/.zig-cache
          key: zig-tests-dbg-${{ runner.os }}-${{hashFiles('**/*.zig','content')}}
          restore-keys: |
            zig-tests-dbg-${{ runner.os }}-
            zig-tests-dbg-
            zig-tests-
            zig-

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglfw3 libglfw3-dev
          version: glfw
      - name: Run tests
        run: |
          zig build test

      - name: Summary results
        if: always()
        run: |
          cat zig-out/test_output.md >> $GITHUB_STEP_SUMMARY
  tests-rel:
    runs-on: ubuntu-latest
    name: Run tests (release)
    steps:
      - uses: actions/checkout@v3
      - name: Cache zig build
        uses: actions/cache@v4
        env:
          cache-name: cache-zig
        with:
          path: |
            ${{github.workspace}}/.cache/zig
            ${{github.workspace}}/.zig-cache
          key: zig-tests-rel-${{ runner.os }}-${{hashFiles('**/*.zig','content')}}
          restore-keys: |
            zig-tests-rel-${{ runner.os }}-
            zig-tests-rel-
            zig-tests-
            zig-

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglfw3 libglfw3-dev
          version: glfw

      - name: Run tests
        run: |
          zig build test -Doptimize=ReleaseFast
        
      - name: Summary results
        if: always()
        run: |
          cat zig-out/test_output.md >> $GITHUB_STEP_SUMMARY
  itch-upload:
    runs-on: ubuntu-latest
    name: Itch Upload
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/steam_upload' 
    needs: [tests-dbg, tests-rel]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache zig build
        uses: actions/cache@v4
        env:
          cache-name: cache-zig
        with:
          path: |
            ${{github.workspace}}/.cache/zig
            ${{github.workspace}}/.zig-cache
          key: zig-build-itch-rel-${{ runner.os }}-${{hashFiles('**/*.zig','content')}}
          restore-keys: |
            zig-build-itch-rel-${{ runner.os }}-
            zig-build-itch-rel-
            zig-build-itch-
            zig-build-
            zig-
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglfw3 libglfw3-dev
          version: glfw
      - name: Install butler
        uses: remarkablegames/setup-butler@v2
      - name: Install mingw
        run: sudo apt-get install gcc-mingw-w64 binutils-mingw-w64-x86-64
        shell: bash
      - name: Upload game
        env:
          BUTLER_API_KEY: ${{ secrets.ITCH_API_KEY }}
        run: |
          zig build upload_itch_release