name: Test 
run-name: Run zig tests for commit '${{ github.event.head_commit.message }}' on ${{ github.ref_name }}
on: [push]
jobs:
  tests-dbg:
    runs-on: ubuntu-latest
    name: Run tests 
    steps:
      - uses: actions/checkout@v3
      - name: Cache zig build
        uses: actions/cache@v4
        env:
          cache-name: cache-zig
        with:
          path: |
            ~/.cache/zig
            ~/.zig-cache
          key: zig-tests-dbg-${{ runner.os }}-${{hashFiles('**/*.zig')}}
          restore-keys: |
            zig-tests-dbg-${{ runner.os }}-
            zig-tests-dbg-
            zig-tests-
            zig-

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        run: |
          sudo apt update
          sudo apt install libglfw3 libglfw3-dev

      - name: Run tests
        run: |
          zig build test

      - name: Summary results
        if: always()
        run: |
          cat zig-out/test_output.md >> $GITHUB_STEP_SUMMARY
  tests-rel:
    runs-on: ubuntu-latest
    name: Run tests (release)
    steps:
      - uses: actions/checkout@v3
      - name: Cache zig build
        uses: actions/cache@v4
        env:
          cache-name: cache-zig
        with:
          path: |
            ~/.cache/zig
            ~/.zig-cache
          key: zig-tests-rel-${{ runner.os }}-${{hashFiles('**/*.zig')}}
          restore-keys: |
            zig-tests-rel-${{ runner.os }}-
            zig-tests-rel-
            zig-tests-
            zig-

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        run: |
          sudo apt update
          sudo apt install libglfw3 libglfw3-dev

      - name: Run tests
        run: |
          zig build test -Doptimize=ReleaseFast
        
      - name: Summary results
        if: always()
        run: |
          cat zig-out/test_output.md >> $GITHUB_STEP_SUMMARY
  steam_upload:
    runs-on: ubuntu-latest
    name: Steam Upload
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/steam_upload' 
    needs: [tests-dbg, tests-rel]
    steps:
      - uses: actions/checkout@v3
      - name: Setup SteamCMD
        id: steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Cache steam login
        id: cache-steam
        uses: actions/cache@v4
        env:
          cache-name: cache-steam
        with:
          path: |
            ${{ env.STEAM_DIR }}
            ${{ env.STEAM_TEMP }}
          key: steamcmd
          restore-keys: steamcmd
          save-always: true
      - name: Cache zig build
        uses: actions/cache@v4
        env:
          cache-name: cache-zig
        with:
          path: |
            ~/.cache/zig
            ~/.zig-cache
          key: zig-build-steam=${{ runner.os }}-${{hashFiles('**/*.zig')}}
          restore-keys: |
            zig-build-steam-${{ runner.os }}-
            zig-build-steam-
            zig-build-
            zig-
      - name: Steamworks login
        if: ${{ steps.cache-steam.outputs.cache-hit != 'true' }}
        run: |
          steamcmd +login preston3410 ${{ secrets.STEAM_PASSWORD }} +quit 
      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        run: |
          sudo apt update
          sudo apt install libglfw3 libglfw3-dev 
      - name: Install mingw
        run: |
          sudo apt update
          sudo apt install gcc-mingw-w64
          
      - name: Uploads to steam
        run: |
          zig build upload_steam
  gen-changelog:
    runs-on: ubuntu-latest
    name: Generate changelog
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache zig build
        uses: actions/cache@v4
        env:
          cache-name: cache-zig
        with:
          path: |
            ~/.cache/zig
            ~/.zig-cache
          key: zig-build-changelog-${{ runner.os }}-${{hashFiles('**/*.zig')}}
          restore-keys: |
            zig-build-changelog-${{ runner.os }}-
            zig-build-changelog-
            zig-build-
            zig-

      - name: Setup Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.15.2
      - name: Install glfw
        run: |
          sudo apt update
          sudo apt install libglfw3 libglfw3-dev
      - name: Generate changelog
        run: |
          zig build changelog

      - name: Summary results
        if: always()
        run: |
          cat zig-out/changelog.edf >> $GITHUB_STEP_SUMMARY




